### ISSUE TITLE
Please change favico 

### ISSUE THREAD

**Issue by Sauloxd** [guilhermemamprin/webshoes-frontend#11]
Art. 184. Violar direitos de autor e os que lhe são conexos:(Redação dada pela Lei nº 10.695, de 1º.7.2003)

Pena- detenção, de 3 (três) meses a 1 (um) ano, ou multa. (Redação dada pela Lei nº 10.695, de 1º.7.2003)

§ 1o Se a violação consistir em reprodução total ou parcial, com intuito de lucro direto ou indireto, por qualquer meio ou processo, de obra intelectual, interpretação, execução ou fonograma, sem autorização expressa do autor, do artista intérprete ou executante, do produtor, conforme o caso, ou de quem os represente: (Redação dada pela Lei nº 10.695, de 1º.7.2003)

Pena- reclusão, de 2 (dois) a 4 (quatro) anos, e multa. (Redação dada pela Lei nº 10.695, de 1º.7.2003)

![image](https://cloud.githubusercontent.com/assets/11878589/16816633/2aa427e6-4915-11e6-8ded-5705b2097134.png)

Se não trocar vou processar vcs.

**Comment by guilhermemamprin** [comment]
@Sauloxd Claramente é diferente, tanto pela qualidade quanto pela letra representada. O sr está deveras equivocado

**Comment by Sauloxd** [comment]
🎱
